# Generated by Django 4.1.7 on 2023-03-02 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='favoritebook',
            name='user',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
    ]
