# Generated by Django 4.1.7 on 2023-02-20 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_full_name_author_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='first_name',
        ),
    ]
