# Generated by Django 4.1.7 on 2023-03-02 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_cart_books_name_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteBook',
        ),
    ]
